menu:
  Home: /
  Archives: /archives
rss: /atom.xml

archive_date_format: MMM DD
fancybox: true

duoshuo_shortname: curry2015

google_analytics:
favicon: http://s0.qhimg.com/static/79ec3f5e5536f764/favicon.ico
